### ISSUE TITLE
Nothing happens after running seed & web app

### ISSUE THREAD

**Issue by weedkiller** [WebVella/WebVella-ERP-Seed#1]
Hello, I dont get an error any page served when I run the seed. I also dont see tables in the PostGres DB.

Can you tell me how I can resolve this. Does it need any additional driver besides the install.

Thanks

**Comment by bzashev** [comment]
Besides the install you will need just a created empty database and a connection string.
Check out here for more info https://webvella.com/documents/developer/introduction/getting-started

**Comment by weedkiller** [comment]
Awesome thanks!
